[package]
name = "celestica-crdt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.33"

bytecheck = { version = "0.6.9", optional = true }
rkyv = { version = "0.7.39", features = ["validation"], optional = true }

[features]
# Enables (de)serialization support for all data types.
rkyv-support = ["rkyv", "bytecheck"]
